### ISSUE TITLE
paper 1.18.1 invalid

### ISSUE THREAD

**Issue by Shizuri23** [Nats-ji/paper-sand-dupe-unpatched#1]
https://user-images.githubusercontent.com/46082179/153552267-9ef9fe8e-8e7e-4462-b967-371031a7f14e.mp4

<img width="659" alt="image" src="https://user-images.githubusercontent.com/46082179/153552354-77ad4557-9816-4f85-8f6c-674d35958937.png">

**Comment by Nats-ji** [comment]
我测试了一下可以正常复制沙子。
你看看是不是安装了反作弊插件屏蔽了复制沙子(我知道NoCheatPlus会默认屏蔽复制沙子)。或者主世界的区块没有被加载。
