### ISSUE TITLE
don´t work

### ISSUE THREAD

**Issue by Bilu2711** [Nats-ji/paper-sand-dupe-unpatched#12]
baixei o arquivo e coloquei na pasta versions do meu servidor no lugar do outro arquivo paper, mas mesmo assim nao funciona

**Comment by Bilu2711** [comment]
nao sei em qual diretório eu coloco o arquivo .jar

**Comment by Nats-ji** [comment]
you need to rename the downloaded jar to the original paper jar file name.

**Comment by Bilu2711** [comment]
eu fiz isso, mas ele baixa um novo sempre que reinicio o servidor

**Comment by Quinnnnnq** [comment]
please check your boot file like start.bat/sh etc.
