### ISSUE TITLE
Forked and found unable to compile Minecraft 1.21 core

### ISSUE THREAD

**Issue by Ziyang-Bai** [Nats-ji/paper-sand-dupe-unpatched#13]
I followed the instructions and successfully compiled the core of version 1.20.1. However, when compiling version 1.21, an action error occurred and the operation could not be completed
Reproduction error
Set config.json to 1.21
Execute Action

**Comment by Nats-ji** [comment]
paper官方服务端在1.21版本之后添加了开启刷沙的选项，你不需要用这个项目自己编译了。
