### ISSUE TITLE
刷县级无法使用

### ISSUE THREAD

**Issue by Jam-04** [Nats-ji/paper-sand-dupe-unpatched#14]
如果我是用了这个，刷线机就用不了了

**Comment by Nats-ji** [comment]
我没有修复刷线机，建议用Purpurmc

**Comment by Jam-04** [comment]
不过到我们服这个阶段都要搞刷沙机了，刷线机貌似也没啥用了

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年08月28日 23:04 |
| 收件人 | Nats-ji/paper-sand-dupe-unpatched ***@***.***> |
| 抄送人 | Jam-04 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [Nats-ji/paper-sand-dupe-unpatched] 刷县级无法使用 (Issue #14) |

我没有修复刷线机，建议用Purpurmc

**Comment by Nats-ji** [comment]
如果你想要原版的体验并且高性能的服务端的话，我建议你改用fabric端搭配性能优化mod，性能会比paper好很多。参考https://www.youtube.com/watch?v=XjjXYrMK4qw

**Comment by Jam-04** [comment]
你会继续做1.21的吗
