### ISSUE TITLE
But where can I del this patch in PurpurMC/Purpur?

### ISSUE THREAD

**Issue by z0z0r4** [Nats-ji/paper-sand-dupe-unpatched#2]
I can't find Fix-sand-duping.patch in [Purpur](https://github.com/PurpurMC/Purpur/tree/ver/1.18.2/patches/server)
It doesn't work well with its own options, I want to remove this complement instead of editing the config
thx :)

**Comment by Nats-ji** [comment]
I don't know about purpur. this repo is for patching paper.
if you don't need other features purpur provides, you can just use this instead.

**Comment by z0z0r4** [comment]
hmmmm, thank you
