### ISSUE TITLE
我能够获得action中编译出的jar吗

### ISSUE THREAD

**Issue by z0z0r4** [Nats-ji/paper-sand-dupe-unpatched#3]
我需要些指定build的服务端…但我没找到哪里可以获得
他们不在release里面

或者我怎么才能手动修改以自行build一个去掉刷沙修复的paper端

**Comment by Nats-ji** [comment]
你fork后把 `index.js` 里的[这一行](https://github.com/Nats-ji/paper-sand-dupe-unpatched/blob/f426ee9f1a6e36b062186f3b78b5634cce27e999/index.js#L18)括号里加上你想要的版本号试试。比如编译1.16.2的话，改成：
```js
let info = await get_info(gh_repo, "1.16.2");
```
然后action就会自动编译了。

**Comment by z0z0r4** [comment]
hmmmm，你确定1.16.2能直接处理吗
我昨天好像看了看paper 1.17以下的分支，似乎...都没找到patch文件夹

**Comment by Nats-ji** [comment]
我没试过。这个脚本是1.18的时候写的。 好像paper在1.17之后把文件夹名字改了，等回来我看看

**Comment by Nats-ji** [comment]
https://github.com/Nats-ji/paper-sand-dupe-unpatched/releases/tag/1.17.1-411
1.17.1我编译上传了。1.17之前的这个脚本目前没法编译
