### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by shalevc1098** [Nats-ji/paper-sand-dupe-unpatched#6]
Hello, I've downloaded the latest unpatched version from the releases, but when I tried to check if the sand dupe works, it didn't. Did I do something wrong?

**Comment by Nats-ji** [comment]
https://user-images.githubusercontent.com/13299626/188272009-539e3142-afaa-448a-9716-f97ced0c0b4b.mp4

Works for me. Test world: https://www.youtube.com/watch?v=YDowkQh-TIg
You need to make sure the overworld side is chunk loaded either with a chunk loader or with a player. Some anti-cheat plugins also patches sand duping.

**Comment by shalevc1098** [comment]
> Owner

I used KelpMC's better sand farm and there was a chapter in the video where he shows how to check if the dupe works on a server. I used his method but it didn't work on paper (even the unpatched one) but worked on vanilla.

**Comment by Nats-ji** [comment]
can you send the link

**Comment by shalevc1098** [comment]
> can you send the link

https://www.youtube.com/watch?v=Uq3mQhk20MQ&ab_channel=KelpMC

**Comment by Nats-ji** [comment]
https://user-images.githubusercontent.com/13299626/188279873-385952be-045d-4939-b69a-b4ff57d93d75.mp4

I downloaded his save, works just fine though

**Comment by shalevc1098** [comment]
> 
> https://user-images.githubusercontent.com/13299626/188279873-385952be-045d-4939-b69a-b4ff57d93d75.mp4
> 
> I downloaded his save, works just fine though

Can you try to do his test and check if it works?

**Comment by Nats-ji** [comment]
The test won't work because it's a part of an anti griefing patch from PaperMC (or SpigotMC). it prevents griefers from throwing a million items to the End and crashing the server. Blocks and items above the End platform will be auto cleared when the next entity comes through.

**Comment by shalevc1098** [comment]
> The test won't work because it's a part of an anti griefing patch from PaperMC (or SpigotMC). it prevents griefers from throwing a million items to the End and crashing the server. Blocks and items above the End platform will be auto cleared when the next entity comes through.

Oh, so how does the sand machine works? It does the same thing, no?

**Comment by Nats-ji** [comment]
the sand machine pushes the sand outside the End platform before it's getting cleared.
