### ISSUE TITLE
How to make it work 

### ISSUE THREAD

**Issue by XueYin114514** [Nats-ji/paper-sand-dupe-unpatched#8]
I downloaded the .jar
where should i put it in my server flies
下载之后要放在服务端的哪个文件夹里

**Comment by XueYin114514** [comment]
1.19.2 paper 端

**Comment by XueYin114514** [comment]
![image](https://user-images.githubusercontent.com/117132106/199376328-08a645a2-7c41-4890-9c8f-81d507c7acbc.png)

**Comment by InoryS** [comment]
这就是服务端，把你的原来的 paper.jar 服务端换成本仓库的即可。

**Comment by XueYin114514** [comment]
替换了之后每次重启服务器都会把原来的paper.jar重新安装上，这是怎么回事

**Comment by XueYin114514** [comment]
![@QL6 )@L0)8R2E~_Y~I3 23](https://user-images.githubusercontent.com/117132106/200161821-c0ef8fe7-bd14-4677-a934-286319000e12.png)

**Comment by Nats-ji** [comment]
你怎么还有个versions文件夹。一般服务端都是直接放在根目录。估计是面板服的蜜汁操作？你把下载的jar重命名替换原本的服务端试试。不行你就问你服务器供应商怎么安装自定义服务端

**Comment by XueYin114514** [comment]
我把服务器的启动核心换成了这个，可以刷沙子了，确实解决了问题，作者nb，谢谢
